{strip}

<div class="panel panel-default area-doc hidden_area" id="{$id}">
      <div class="panel-body">

          <ol class="breadcrumb">
            <li><a href="#">Administrativo</a></li>
            <li><a href="#">Funções JS e CSS</a></li>
            <li class="active">{$texto}</li>
          </ol>




          <hr />


<!-- ==================== -->
<h3 class="p-t-15"><span class="text-uppercase">Classes CSS de Texto</span> <code> Usar na view </code></h3>

<pre>
<strong>TEXTO MAIUSCULO</strong>

text-uppercase</pre>

<pre>
<strong>TEXTO MINUSCULO</strong>

text-lowercase</pre>

<pre>
<strong>TEXTO MAIUSCULO E MINUSCULO</strong>

text-capitalize</pre>

<pre>
<strong>TEXTO ALINHADO A ESQUERDA</strong>

text-left</pre>

<pre>
<strong>TEXTO ALINHADO A DIREITA</strong>

text-right</pre>

<pre>
<strong>TEXTO ALINHADO NO CENTRO</strong>

text-center</pre>


<!-- ==================== -->
<h3 class="p-t-15"><span class="text-uppercase">Classes CSS de Alinhamento</span> <code> Usar na view </code></h3>

<pre>
<strong>Bloco Alinhado a Esquerda</strong>

pull-left</pre>

<pre>
<strong>Bloco Alinhado a Direita</strong>

pull-right</pre>

<pre>
<strong>Centralizo texto de um bloco</strong>

center-block</pre>


<!-- ==================== -->
<h3 class="p-t-15"><span class="text-uppercase">Classes Gerais CSS</span> <code> Usar na view </code></h3>

<pre>
<strong>Oculto Elementos</strong>

<b>hidden_area</b></pre>

<pre>
<strong>Zero Valores de Elementos</strong>

<b>no-border</b> <br />
<b>no-padding</b> <br />
<b>no-margin</b> <br />
<b>no-shadow</b></pre>

<pre>
<strong>Font Weights</strong>

<b>f-300</b> <br />
<b>f-400</b> <br />
<b>f-500</b> <br />
<b>f-700</b></pre>

<pre>
<strong>Position Classes</strong>

<b>p-relative</b> <br />
<b>p-absolute</b> <br />
<b>p-fixed</b> <br />
<b>p-static</b></pre>

<pre>
<strong>Corto e Centralizo uma imagem (Obrigatório o width e height)</strong>

<b>center-cropped</b></pre>

<pre>
<strong>Classe com tamanhos de fontes</strong>

<b>f-s-2 até f-s-34 (de 2 em 2)</b></pre>

<pre>
<strong>Espaço entre linhas Line-Height</strong>

<b>line-height-m</b> <br />
<b>line-height-g</b> </pre>

<pre>
<strong>Margin top, left, bottom e right com tamanhos definidos</strong>

<b>m-t-5 até m-t-50 - top (de 5 em 5) </b>
<b>m-l-5 até m-l-50 - left (de 5 em 5) </b>
<b>m-b-5 até m-b-50 - bottom (de 5 em 5) </b>
<b>m-r-5 até m-r-50 - right (de 5 em 5) </b> </pre>

<pre>
<strong>Padding top, left, bottom e right com tamanhos definidos</strong>

<b>p-t-5 até p-t-50 - top (de 5 em 5) </b>
<b>p-l-5 até p-l-50 - left (de 5 em 5) </b>
<b>p-b-5 até p-b-50 - bottom (de 5 em 5) </b>
<b>p-r-5 até p-r-50 - right (de 5 em 5) </b> </pre>


<!-- ==================== -->
<h3 class="p-t-15"><span class="text-uppercase">Labels CSS</span> <code> Usar na view </code></h3>

<pre>
<strong>Labels coloridos</strong>

<div class="label-danger m-b-5 p-l-5 p-t-5 p-r-5 p-b-5">label-danger</div>
<div class="label-info m-b-5 p-l-5 p-t-5 p-r-5 p-b-5">label-info</div>
<div class="label-warning m-b-5 p-l-5 p-t-5 p-r-5 p-b-5">label-warning</div>
<div class="label-primary m-b-5 p-l-5 p-t-5 p-r-5 p-b-5">label-primary</div>
<div class="label-success m-b-5 p-l-5 p-t-5 p-r-5 p-b-5">label-success</div>
<div class="label-default2 m-b-5 p-l-5 p-t-5 p-r-5 p-b-5">label-default2</div></pre>


<!-- ==================== -->
<h3 class="p-t-15"><span class="text-uppercase">Classes CSS de Cor de Background</span> <code> Usar na view </code></h3>

<pre>
<strong>Cor de Fundo</strong>

<div class="bg-red p-l-5 p-r-5 p-b-5 p-t-5 m-b-5">bg-red</div>
<div class="bg-yellow p-l-5 p-r-5 p-b-5 p-t-5 m-b-5">bg-yellow</div>
<div class="bg-aqua p-l-5 p-r-5 p-b-5 p-t-5 m-b-5">bg-aqua</div>
<div class="bg-blue p-l-5 p-r-5 p-b-5 p-t-5 m-b-5">bg-blue</div>
<div class="bg-light-blue p-l-5 p-r-5 p-b-5 p-t-5 m-b-5">bg-light-blue</div>
<div class="bg-green p-l-5 p-r-5 p-b-5 p-t-5 m-b-5">bg-green</div>
<div class="bg-navy p-l-5 p-r-5 p-b-5 p-t-5 m-b-5">bg-navy</div>
<div class="bg-teal p-l-5 p-r-5 p-b-5 p-t-5 m-b-5">bg-teal</div>
<div class="bg-olive p-l-5 p-r-5 p-b-5 p-t-5 m-b-5">bg-olive</div>
<div class="bg-lime p-l-5 p-r-5 p-b-5 p-t-5 m-b-5">bg-lime</div>
<div class="bg-orange p-l-5 p-r-5 p-b-5 p-t-5 m-b-5">bg-orange</div>
<div class="bg-fuchsia p-l-5 p-r-5 p-b-5 p-t-5 m-b-5">bg-fuchsia</div>
<div class="bg-purple p-l-5 p-r-5 p-b-5 p-t-5 m-b-5">bg-purple</div>
<div class="bg-maroon p-l-5 p-r-5 p-b-5 p-t-5 m-b-5">bg-maroon</div>
<div class="bg-black p-l-5 p-r-5 p-b-5 p-t-5 m-b-5">bg-black</div>
<div class="bg-red-active p-l-5 p-r-5 p-b-5 p-t-5 m-b-5">bg-red-active</div>
<div class="bg-yellow-active p-l-5 p-r-5 p-b-5 p-t-5 m-b-5">bg-yellow-active</div>
<div class="bg-aqua-active p-l-5 p-r-5 p-b-5 p-t-5 m-b-5">bg-aqua-active</div>
<div class="bg-blue-active p-l-5 p-r-5 p-b-5 p-t-5 m-b-5">bg-blue-active</div>
<div class="bg-light-blue-active p-l-5 p-r-5 p-b-5 p-t-5 m-b-5">bg-light-blue-active</div>
<div class="bg-green-active p-l-5 p-r-5 p-b-5 p-t-5 m-b-5">bg-green-active</div>
<div class="bg-navy-active p-l-5 p-r-5 p-b-5 p-t-5 m-b-5">bg-navy-active</div>
<div class="bg-teal-active p-l-5 p-r-5 p-b-5 p-t-5 m-b-5">bg-teal-active</div>
<div class="bg-olive-active p-l-5 p-r-5 p-b-5 p-t-5 m-b-5">bg-olive-active</div>
<div class="bg-lime-active p-l-5 p-r-5 p-b-5 p-t-5 m-b-5">bg-lime-active</div>
<div class="bg-orange-active p-l-5 p-r-5 p-b-5 p-t-5 m-b-5">bg-orange-active</div>
<div class="bg-fuchsia-active p-l-5 p-r-5 p-b-5 p-t-5 m-b-5">bg-fuchsia-active</div>
<div class="bg-purple-active p-l-5 p-r-5 p-b-5 p-t-5 m-b-5">bg-purple-active</div>
<div class="bg-maroon-active p-l-5 p-r-5 p-b-5 p-t-5 m-b-5">bg-maroon-active</div>
<div class="bg-black-active p-l-5 p-r-5 p-b-5 p-t-5 m-b-5">bg-black-active</div>
<div class="bg-teal-gradient p-l-5 p-r-5 p-b-5 p-t-5 m-b-5">bg-teal-gradient</div>
<div class="bg-light-blue-gradient p-l-5 p-r-5 p-b-5 p-t-5 m-b-5">bg-light-blue-gradient</div>
<div class="bg-blue-gradient p-l-5 p-r-5 p-b-5 p-t-5 m-b-5">bg-blue-gradient</div>
<div class="bg-aqua-gradient p-l-5 p-r-5 p-b-5 p-t-5 m-b-5">bg-aqua-gradient</div>
<div class="bg-yellow-gradient p-l-5 p-r-5 p-b-5 p-t-5 m-b-5">bg-yellow-gradient</div>
<div class="bg-purple-gradient p-l-5 p-r-5 p-b-5 p-t-5 m-b-5">bg-purple-gradient</div>
<div class="bg-green-gradient p-l-5 p-r-5 p-b-5 p-t-5 m-b-5">bg-green-gradient</div>
<div class="bg-red-gradient p-l-5 p-r-5 p-b-5 p-t-5 m-b-5">bg-red-gradient</div>
<div class="bg-black-gradient p-l-5 p-r-5 p-b-5 p-t-5 m-b-5">bg-black-gradient</div>
<div class="bg-maroon-gradient p-l-5 p-r-5 p-b-5 p-t-5 m-b-5">bg-maroon-gradient</div></pre>


<!-- ==================== -->
<h3 class="p-t-15"><span class="text-uppercase">Classes CSS de Cor de Texto</span> <code> Usar na view </code></h3>

<pre>
<strong>Cor de Texto</strong>

<span class="text-red"><strong>text-red</strong> </span><br />
<span class="text-yellow"><strong>text-yellow</strong></span><br />
<span class="text-aqua"><strong>text-aqua</strong></span><br />
<span class="text-blue"><strong>text-blue</strong> </span><br />
<span class="text-black"><strong>text-black</strong></span><br />
<span class="text-light-blue"><strong>text-light-blue</strong> </span> <br />
<span class="text-green"><strong>text-green</strong> </span><br />
<span class="text-gray"><strong>text-gray </strong></span><br />
<span class="text-navy"><strong>text-navy</strong> </span><br />
<span class="text-teal"><strong>text-teal </strong></span><br />
<span class="text-olive"><strong>text-olive</strong> </span><br />
<span class="text-lime"><strong>text-lime</strong> </span><br />
<span class="text-orange"><strong>text-orange</strong> </span><br />
<span class="text-fuchsia"><strong>text-fuchsia </strong></span><br />
<span class="text-purple"><strong>text-purple </strong></span><br />
<span class="text-maroon"><strong>text-maroon</strong> </span></pre>

      </div>
</div>
