{strip}

<div class="panel panel-default area-doc hidden_area" id="{$id}">
      <div class="panel-body">

          <ol class="breadcrumb">
            <li><a href="#">Administrativo</a></li>
            <li class="active">{$texto}</li>
          </ol>

          <p class="f-s-16">
             As notificações do painel administrativo servem para exibir informações aos usuários, ex: notificação de aprovação de um usuário, notificação de produtos e outras.
          </p>

          <hr />


<!-- ==================== -->
<h3 class="p-t-20"><span class="text-uppercase">Sistema de Notificações</span> <code> Usar no Controller </code></h3>

<pre>
<strong>INSIRO UMA NOTIFICAÇÃO</strong>

//INSTANCIO CLASSE DO CORE CONTROLLER
$this->core->includeControllerView('core',$this->dir_app); //Incluo arquivo coreController.php
$controller_geral = new coreController();

// $class_icone - Font icons = font awesome, glyphicons
// $mensagem - Mensagem da notificação
// $url_destino - páginas do administrativo
// $usuario_id - id do usuário do administrativo
// $texto_botao_acao - Texto do botão de Ação exemplo: Abrir

//INSIRO NOTIFICAÇÃO
$this->controller_geral->insiro_notificacao($class_icone,$mensagem,$url_destino = null,$usuario_id,$texto_botao_acao = null)</pre>



      </div>
</div>
