{strip}

    <!-- TITULO -->
    {include file="modulos/geral/pdf/includes/header.phtml"}

    <!-- ARRAY -->
    {foreach $array as $i}

        <!-- ID, DATA E HORA -->
        {include file="modulos/geral/pdf/includes/content_header.phtml"}

        <!-- OUTROS CAMPOS -->
        {foreach $campos as $i2}

            <!-- Usuario -->
            {if $i2 == 'usuario'}
                {if $i.nome != ""} <strong>Usuario:</strong> {$i.nome} {/if}
            {/if}

			<!-- IP -->
            {if $i2 == 'ip'}
                {if $i.IP != ""} - <strong>IP:</strong> {$i.IP} {/if}
            {/if}

			<!-- SO -->
            {if $i2 == 'so'}
                {if $i.SO != ""} - <strong>SO:</strong> {$i.SO} <br>{/if}
            {/if}

			<!-- Navegador -->
            {if $i2 == 'navegador'}
                {if $i.navegador != ""} <strong>Navegador:</strong> {$i.navegador} {/if}
            {/if}

			<!-- IDIOMA -->
            {if $i2 == 'idioma'}
                {if $i.idioma != ""} - <strong>Idioma:</strong> {$i.idioma} {/if}
            {/if}

			<!-- hota -->
			{if $i2 == 'hora'}
				{if $i.hora != ""} - <strong>Ultima hora:</strong> {$i.hora|date_format:"%d/%m/%Y"} ás {$i.hora|date_format:"%H:%M:%S"} {/if}
			{/if}


        {/foreach}

        <br />
        <br />
        <hr />

    {/foreach}
