{strip}

<div style="font-family:arial">
<h3>Olá {$nome|upper},</h3>
<p>

    Ocorreram várias tentativas mal sucedidas de acesso a sua conta <strong> {$nome_empresa} </strong>  <br /><br />

    <strong> {$smarty.now|date_format: "%d/%m/%Y"} ás {$smarty.now|date_format: "%H:%M:%S"}.</strong> <br />
    <strong>Sistema operacional:</strong> {$so} <br />
    <strong>Navegador:</strong>	{$navegador} <br />
    <strong>Endereço IP:</strong> {$ip} <br /><br />

    Se você fez isso, você pode desconsiderar este e-mail com segurança. <br />
    Se você não fez isso, altere sua senha.</a> <br />
<br /><br />

</p>

{$assinatura_email}
</div>
