{strip}

<div style="font-family:arial">
<h3>Bem-Vindo, {$nome|upper}</h3>

<p>

Você foi cadastrado com sucesso no sistema da <strong>{$nome_empresa}.</strong> <br />
Clique no botão abaixo para finalizar seu cadastro. <br />
<br />
<a style="background-color:#0b8682;color:#FFF;padding:8px;text-decoration:none;font-size:16px;" href="http://{$site}{$path_raiz}cadastro/{$id}/{$token}"> Finalize seu Cadastro </a>

</p>
<br />

{$assinatura_email}
</div>
