{strip}

<div class="box-header with-border">
      <h3 class="box-title"><i class="{$icon_titulo}"></i> {$titulo}</h3>
      <div class="box-tools pull-right">
          <span class="titulo-detalho-esq2 hidden_area remove_area_responsive show_area_responsive">
              {if $status_btn_editar == true}
              <a href="{$path_atual}{$url_pagina}/editar/{$id}" class="btn-resp2" title="Editar" data-title="tooltip" data-placement="bottom"><i class="fa fa-pencil-square-o"></i> EDITAR</a>
              {/if}
			  {if $pdf == ''}
              <a href="{$action_exp_pdf}&id={$id}&exp=true" class="btn-resp2" target="_blank" title="Exportar para PDF" data-title="tooltip" data-placement="bottom"><i class="fa fa-file-pdf-o"></i> EXPORTAR PDF</a>
			  {/if}
			  {if $imprimir == ''}
			  	<a href="javascript:void(0);" id="imprimir_area" class="btn-resp2" title="Imprimir" data-title="tooltip" data-placement="bottom"><i class="fa fa-print"></i> IMPRIMIR</a>
			  {/if}
			  <a href="javascript:void(0);" class="mostra_area btn-resp2" hide_area=".area_boxes_pers" title="Fechar" data-title="tooltip" data-placement="bottom"><i class="fa fa-remove"></i> FECHAR</a>
          </span>
          <span class="titulo-detalho-esq2 hidden_area show_area_responsive1">
              {if $status_btn_editar == true}
              <a href="{$path_atual}{$url_pagina}/editar/{$id}" class="btn-resp2" title="Editar" data-title="tooltip" data-placement="bottom"><i class="fa fa-pencil-square-o"></i> </a>
              {/if}
			  {if $pdf == ''}
              <a href="{$action_exp_pdf}&id={$id}&exp=true" class="btn-resp2" target="_blank" title="Exportar para PDF" data-title="tooltip" data-placement="bottom"><i class="fa fa-file-pdf-o"></i> </a>
			  {/if}
			  {if $imprimir == ''}
			  <a href="javascript:void(0);" class="btn-resp2" id="imprimir_area" title="Imprimir" data-title="tooltip" data-placement="bottom"><i class="fa fa-print"></i> </a>
			  {/if}
			  <a href="javascript:void(0);" class="mostra_area btn-resp2" hide_area=".area_boxes_pers" title="Fechar" data-title="tooltip" data-placement="bottom"><i class="fa fa-remove"></i> </a>
          </span>
      </div>
</div>
