{strip}

    <div class="{$col}">
          <div class="info-box bg-light-blue-active">
            <span class="info-box-icon info-box-icon2"><i class="fa fa-envelope"></i></span>
            <div class="info-box-content p-l-15">
              <span title="E-MAILS ENVIADOS - ADMIN" class="info-box-number info-box-number2 p-t-15"> E-MAILS ENVIADOS</span>
              <p class=" p-t-5 font-maior-box-totais">
                  <span>{$total_registros_adm[0].total_email_enviados_dia_admin}</span> Hoje <br />
                  <span>{$total_registros_adm[0].total_email_enviados_semana_admin}</span> Semana <br />
                  <span>{$total_registros_adm[0].total_email_enviados_mes_admin}</span> Mês
              </p>
            </div>
          </div>
    </div>
