{strip}
{include file="modulos/geral/includes/head.phtml"}
{include file="modulos/geral/includes/header.phtml"}
{include file="modulos/geral/includes/sidebar.phtml"}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
<div class="row">
<div class="col-md-12">

    <!-- SAUDACAO -->
    <div style="margin-top:-35px;" class="col-md-12">
        <section class="content-header">
              <h1>
                <small><strong>{$saudacao_hora|upper} - {$nome_usuario_ativo|upper}</strong> - {$saudacao_adm} </small>
                <small class="pull-right p-t-5 hidden-md hidden-sm hidden-xs"><i class="fa fa-circle text-success"></i> <strong>Ativo:</strong> {$so_ativo}, {$navegador_ativo} - IP: {$ip_ativo}</small>
              </h1>
              <div class="border-bottom-solid"></div>
        </section>
    </div>
    <section>


        <!-- ==================================================================================================== -->
        <!-- AREA ATALHOS -->
        {if $total_registros_adm[0].total_notificacoes_admin == 0}
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        {else}
            <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
        {/if}

            <!-- TITULO -->
            <div class="row col-md-12 col-sm-12 col-xs-12 m-t-5">
                <section class="content-header">
                      <h1 class="titulo-divide"><i class="fa fa-share"></i> Links Úteis</h1>
                </section>
            </div>
            {if $total_registros_adm[0].total_notificacoes_admin == 0}
                {include file="modulos/geral/home/area_atalhos.phtml" col="col-lg-4 col-md-4 col-sm-12 col-xs-12"}
            {else}
                {include file="modulos/geral/home/area_atalhos.phtml" col="col-lg-12 col-md-12 col-sm-12 col-xs-12"}
            {/if}
        </div>
        <!-- fim área de atalhos -->


        <!-- ==================================================================================================== -->
        <!-- AREA NOTIFICAÇÕES -->
        {if $total_registros_adm[0].total_notificacoes_admin >= 1}
            <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">

                    <!-- TITULO -->
                    <div class=" col-md-12 col-sm-12 col-xs-12 m-t-5">
                        <div class="row">
                        <section class="content-header">
                              <h1 class="titulo-divide"><i class="fa fa-list"></i> Informações Gerais</h1>
                        </section>
                    </div>
                    </div>

                    {if $status_listagem_mod3 == true}
                    <!-- ADMIN NOTIFICACOES -->
                        {include file="modulos/geral/home/lista_notificacoes_admin.phtml" col="col-md-12 col-sm-12 col-xs-12"}
                    {else}
                        {include file="modulos/geral/home/lista_notificacoes_admin.phtml" col="col-lg-6 col-md-6 col-sm-12 col-xs-12"}
                    {/if}

                    {if $status_listagem_mod3 == true}
                    <!-- AREA DE TOTAIS ADMIN -->
                        {if $status_usuario_online == true}
                            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                        {else}
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        {/if}
                            <div class="row">
                                {if $status_usuario_online == true}
                                    {include file="modulos/geral/home/area_total_sms_enviados_admin.phtml" col="col-lg-12 col-md-12 col-sm-12 col-xs-12"}
                                    {include file="modulos/geral/home/area_total_emails_enviados_admin.phtml" col="col-lg-12 col-md-12 col-sm-12 col-xs-12"}
                                {else}
                                    {include file="modulos/geral/home/area_total_sms_enviados_admin.phtml" col="col-lg-6 col-md-6 col-sm-12 col-xs-12"}
                                    {include file="modulos/geral/home/area_total_emails_enviados_admin.phtml" col="col-lg-6 col-md-6 col-sm-12 col-xs-12"}
                                {/if}
                            </div>
                        </div>
                    {/if}

                    {if $status_usuario_online == true}
                    <!-- ADMIN USUARIOS ONLINE -->
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                        <div class="row">
                            {include file="modulos/geral/home/lista_usuarios_online_admin.phtml" col="col-lg-12 col-md-12 col-sm-12 col-xs-12"}
                        </div>
                    </div>
                    {/if}

            </div>
            <!-- fim área de notificacoes -->

        {else}
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">

                    <!-- TITULO -->
                    <div class="row col-md-12 col-sm-12 col-xs-12 m-t-20">
                        <section class="content-header">
                              <h1 class="titulo-divide"><i class="fa fa-list"></i> Informações Gerais</h1>
                        </section>
                    </div>

                    {if $status_listagem_mod3 == true}
                    <!-- AREA DE TOTAIS ADMIN -->
                        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                            <div class="row">
                                {include file="modulos/geral/home/area_total_sms_enviados_admin.phtml" col="col-lg-12 col-md-12 col-sm-12 col-xs-12"}
                                {include file="modulos/geral/home/area_total_emails_enviados_admin.phtml" col="col-lg-12 col-md-12 col-sm-12 col-xs-12"}
                            </div>
                        </div>
                    {/if}

                    <!-- ADMIN USUARIOS ONLINE -->
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                        <div class="row">
                            {if $status_usuario_online == true}
                                {include file="modulos/geral/home/lista_usuarios_online_admin.phtml" col="col-lg-12 col-md-12 col-sm-12 col-xs-12"}
                            {/if}
                        </div>
                    </div>

            </div>
            <!-- fim área de notificacoes -->
        {/if}



        <!-- ==================================================================================================== -->
        <!-- AREA RELATORIO DE LOGS E LOGS DE ACESSO ADMINISTRATIVO -->
        {if $status_grafico_mod3 == true}

            <!-- TITULO ÁREA -->
            <div class="col-md-12 col-sm-12 col-xs-12 m-t-20">
                <section class="content-header">
                      <h1 class="titulo-divide"><i class="fa fa-pie-chart"></i> Relatórios de Logs do Administrativo</h1>
                </section>
            </div>

            <!-- CONTEUDO ÁREA -->
            <div class="col-md-12 col-sm-12 col-xs-12 margin-bottom">

                <!-- GRAFICOS DE LOGS ADMIN -->
                {if $status_grafico_mod3 == true}
                    {include file="modulos/geral/graficos/grafico_navegadores_mais_utilizados.phtml" col="col-lg-4 col-md-6" height="300" tipo_grafico="pizza"}
                {/if}
                {if $status_grafico_mod3 == true}
                    {include file="modulos/geral/graficos/grafico_so_mais_utilizados.phtml" col="col-lg-4 col-md-6" height="300" tipo_grafico="pizza_3d"}
                {/if}
                {if $status_grafico_mod3 == true}
                    {include file="modulos/geral/graficos/grafico_paginas_mais_utilizados.phtml" col="col-lg-4 col-md-6" height="300" tipo_grafico="anel"}
                {/if}

                <!-- GRAFICOS DE LOGS ACESSO ADMIN -->
                {if $status_grafico_mod3 == true}
                    {include file="modulos/geral/graficos/grafico_total_logs_acesso_usuarios.phtml" col="col-lg-4 col-md-6" height="300" tipo_grafico="anel"}
                {/if}
                {if $status_grafico_mod3 == true}
                    {include file="modulos/geral/graficos/grafico_total_logs_logoff_login.phtml" col="col-lg-4 col-md-6" height="300" tipo_grafico="barra_vertical"}
                {/if}

            </div>
        {/if}




    </section>
</div>
</div>
</div>
<!-- /.content-wrapper -->

{include file="modulos/geral/includes/feedback.phtml"}
{include file="modulos/geral/includes/footer.phtml"}
