{strip}

<!-- ****************************************************************************************************************************** -->
<!-- ****************************************************************************************************************************** -->
    <!-- EXPORTAR PARA PDF -->
    {if $op_exibicao == 'exportar'}

        <!-- ARRAY -->
        <div class="row col-md-12 area-array-detalho">
            <div class="col-md-12">
                <h3>{$titulo|upper} - <span style="font-size:14px;font-weight:normal;">Gerado em {$smarty.now|date_format:"%d/%m/%Y - %H:%M:%S"}</span></h3>
                <hr />
                <!-- ID E DATAS -->
                {include file="modulos/geral/detalho/includes/content_header.phtml"}

				<strong>Usuário: </strong>{$array[0].nome} - <strong>IP: </strong> {$array[0].IP} - <strong>SO: </strong>{$array[0].SO} - <strong>Navegador: </strong>{$array[0].navegador} - <strong>Idioma: </strong>{$array[0].idioma} <br> <strong>Ultima hora: </strong> {$array[0].hora|date_format:"%d/%m/%Y"} ás {$array[0].hora|date_format:"%H:%M:%S"}

			</div>
        </div>
    {/if}

<!-- ****************************************************************************************************************************** -->
<!-- ****************************************************************************************************************************** -->
    <!-- EXIBIR NA TELA -->
    {if $op_exibicao == 'exibir'}

        <!-- TITULO -->
        {include file="modulos/geral/detalho/includes/header.phtml" imprimir="false"}

        <!-- ARRAY -->
		<div class="box-body">
            <div id="area-imprimir" class="area-array-detalho">
                <div class="col-md-12">
                    <!-- ID E DATAS -->
                    {include file="modulos/geral/detalho/includes/content_header.phtml"}



                    <!-- USUARIO -->
                    <div class="col-md-3">
                            <div class="box-body box-profile">
                                {if $array[0].img_perfil == true}
                                <img class="profile-user-img img-responsive img-circle center-cropped" src="{$path_raiz}files/perfil_usuario/p/{$array[0].img_perfil}" >
                                {else}
                                <img class="profile-user-img img-responsive img-circle center-cropped" src="{$path_raiz}adm/view/assets/img/avatar/avatar_h.jpg" >
                                {/if}
                                <h3 class="profile-username text-center">{$array[0].nome} <i title="Online" class="fa fa-circle text-success"></i></h3>
                            </div>
                    </div>

                    <div class="col-md-9">
                            <div class="box-body">
                                <ul class="timeline">
                                    <!-- timeline time label -->
                                    <li class="time-label">
                                        <span class="bg-orange">
                                            <i class="fa fa-clock-o"></i> Cadastrado {$array[0].criado|date_format:"tempo"}
                                        </span>
                                    </li>
                                    <!-- /.timeline-label -->
                                    <!-- timeline item -->
                                    <li>
                                        <i class="fa fa-cog bg-teal"></i>
                                        <div class="timeline-item">
                                            <h3 class="timeline-header"><strong>IP:</strong> {$array[0].IP} - <strong>SISTEMA OPERACIONAL:</strong> {$array[0].SO} </h3>
                                        </div>
                                        <div class="timeline-item">
                                            <h3 class="timeline-header"> <strong>NAVEGADOR:</strong> {$array[0].navegador} - <strong>IDIOMA:</strong> {$array[0].idioma} </h3>
                                        </div>
                                    </li>

                                    <li>
                                        <i class="fa fa-clock-o bg-blue"></i>
                                        <div class="timeline-item">
                                            <div class="timeline-body">
                                                <strong>Último Acesso: </strong> {$array[0].hora|date_format:"%d/%m/%Y"} ás {$array[0].hora|date_format:"%H:%M:%S"}
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                    </div>

                </div>
            </div>
        </div>
    {/if}
