{strip}

<!-- ****************************************************************************************************************************** -->
<!-- ****************************************************************************************************************************** -->
    <!-- EXPORTAR PARA PDF -->
    {if $op_exibicao == 'exportar'}

        <!-- ARRAY -->
        <div class="row col-md-12 area-array-detalho">
            <div class="col-md-12">
                <h3>{$titulo|upper} - <span style="font-size:14px;font-weight:normal;">Gerado em {$smarty.now|date_format:"%d/%m/%Y - %H:%M:%S"}</span></h3>
                <hr />
                <!-- ID E DATAS -->
                {include file="modulos/geral/detalho/includes/content_header.phtml"}

				<strong>Status: </strong>{$array[0].status} <br>
				<strong>Mensagem: </strong>{$array[0].mensagem}

            </div>
        </div>

    {/if}

<!-- ****************************************************************************************************************************** -->
<!-- ****************************************************************************************************************************** -->
    <!-- EXIBIR NA TELA -->
    {if $op_exibicao == 'exibir'}

        <!-- TITULO -->
        {include file="modulos/geral/detalho/includes/header.phtml" imprimir="false" pdf="false"}

        <!-- ARRAY -->
		<div class="box-body">
            <div id="area-imprimir" class="area-array-detalho">
                <div class="col-md-12">
                    <!-- ID E DATAS -->
                    {include file="modulos/geral/detalho/includes/content_header.phtml"}


                  <!-- USUARIO -->
                  <div class="col-md-3">
                          <div class="box-body box-profile">
                              {if $array[0].img_perfil == true}
                              <img class="profile-user-img img-responsive img-circle center-cropped" src="{$path_raiz}files/perfil_usuario/p/{$array[0].img_perfil}" >
                              {else}
                              <img class="profile-user-img img-responsive img-circle center-cropped" src="{$path_raiz}adm/view/assets/img/avatar/avatar_h.jpg" >
                              {/if}
                              <h3 class="profile-username text-center">{$array[0].nome}</h3>
                          </div>
                  </div>

                  <div class="col-md-9">
                          <div class="box-body">
                              <ul class="timeline">
                                  <!-- timeline time label -->
                                  <li class="time-label">
                                      <span class="{if $array[0].status_id == 1 }bg-green{else}bg-orange{/if}">
                                          <i class="fa fa-clock-o"></i> Cadastrado {$array[0].criado|date_format:"tempo"} - {if $array[0].status_id == 1 } <i class="fa fa-check"></i> Lido {else} <i class="fa fa-check-square-o"></i> Não Lido {/if}
                                      </span>
                                  </li>
                                  <!-- /.timeline-label -->
                                  <!-- timeline item -->

                                  <li>
                                      <i class="fa fa-link bg-purple"></i>
                                      <div class="timeline-item">
                                          <h3 class="timeline-header"> <a href="{$path_atual}{$array[0].url_destino}" target="_blank">{$path_atual}{$array[0].url_destino}</a>  </h3>
                                      </div>
                                  </li>

                                  <li>
                                      <i class="fa fa-envelope bg-blue"></i>
                                      <div class="timeline-item">
                                          <div class="timeline-body">
                                              {$array[0].mensagem}
                                          </div>
                                      </div>
                                  </li>
                              </ul>
                          </div>
                  </div>

                </div>
            </div>
        </div>


    {/if}
